import { ApiProperty } from '@nestjs/swagger';
import { IsString, MinLength } from 'class-validator';

export class ResetPasswordDto {
  @ApiProperty({
    description: 'One-time reset token generated by forgot-password endpoint',
    example: 'b8d6e7a4f2f1f6c7d3c8f1b2a4d5e6f7c8d9a0b1c2d3e4f5a6b7c8d9e0f1a2b3',
  })
  @IsString()
  resetToken!: string;

  @ApiProperty({
    description: 'New account password',
    example: 'NewPassword@123',
    minLength: 6,
  })
  @IsString()
  @MinLength(6)
  newPassword!: string;
}
